### PR TITLE
add a save-query-results function for downloading results to a file

### PR DESCRIPTION
**Pull request by zachcp**
hrbrmstr,

Thanks for this excellent package.  I've added a function to retrieve and directly download the results of an Athena query - handy if you expect a large file that you don't want to load into memory. Right now it doesn't do anything fancy like poll for completion but perhaps that could be a follow-on.

zach cp

### CODE REVIEW

**Comment by hrbrmstr** [comment]
Nice! (apologies for the late reply, too…tis been a pretty REDACTED summer). I had debated doing something like this and ended up just putting it in our $DAYJOB private helper package.

Can you also add yourself as an `ctb` in the `DESCRIPTION` file? I can merge the PR right after that.

#ty!

**Comment by hrbrmstr** [comment]
Also, since you're using it in a similar fashion as we do at $DAYJOB, what might your thoughts be on integrating the `future` and/or `promise` packages with this and incorporate a function that will do a check every specified `n` seconds/minutes and auto-download to a specified folder on completion and notify (via some mechanism) on success/failure?

**Comment by zachcp** [comment]
@hrbrmstr  checking for completion is a great idea. I had thought of simply using a `while` statement to keep going until completion-or-timeout but `futures`/`promises` seems like a good match for this problem.

**Comment by zachcp** [comment]
@hrbrmstr,

I've written up a function to run-and-retrieve SQL from Athena. It simply uses a WHILE loop, not the future package.   It was not immediately obvious how to use futures in this case.

**Comment by hrbrmstr** [comment]
I think the `while` solution is perfect. `future` can rly complicate a setup and if it's needed folks can custom implement it.

**Pull request merged**
